apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
data:
  patchlist.json: {{- toYaml .Values.config.patchlist | nindent 4 }}
