apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "webhook.fullname" . }}-tls
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.tls.certificate | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
